imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        # driver:   pdo_sqlite
        # dbname:   %kernel.root_dir%/blog-test.db
        dbname:   blog_test

behat_mink:
    start_url: http://kuba.dev/app_test.php/

behat: ~
